# Generated by Django 5.0.2 on 2024-02-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('false_answer_1', models.CharField(max_length=250)),
                ('false_answer_2', models.CharField(max_length=250)),
                ('false_answer_3', models.CharField(max_length=250)),
                ('true_answer', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Answer',
            },
        ),
    ]
