# Generated by Django 5.0.2 on 2024-02-28 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_number', models.PositiveSmallIntegerField(choices=[(None, 'Номер вопроса'), (1, 'Вопрос 1'), (2, 'Вопрос 2'), (3, 'Вопрос 3'), (4, 'Вопрос 4'), (5, 'Вопрос 5'), (6, 'Вопрос 6'), (7, 'Вопрос 7'), (8, 'Вопрос 8'), (9, 'Вопрос 9'), (10, 'Вопрос 10')])),
                ('question', models.TextField()),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='questions', serialize=False, to='core.answer')),
                ('number_questions', models.PositiveSmallIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.quiz')),
            ],
            options={
                'verbose_name_plural': 'Question',
            },
        ),
    ]
