# Generated by Django 5.0.2 on 2024-02-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='quiz',
        ),
    ]
