# Generated by Django 5.0.2 on 2024-02-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_question_id_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='number_questions',
        ),
    ]
