# Generated by Django 5.0.2 on 2024-02-28 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_question_answer_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.OneToOneField(default=90, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.question'),
            preserve_default=False,
        ),
    ]
