# Generated by Django 5.0.2 on 2024-02-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_answer_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='quiz',
        ),
    ]
