# Generated by Django 5.0.2 on 2024-02-28 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_answer_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name_plural': 'Ответ'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Вопрос'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Викторина'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='number_questions',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='количество вопросов'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='false_answer_1',
            field=models.CharField(max_length=250, verbose_name='Ответ (не верный)'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='false_answer_2',
            field=models.CharField(max_length=250, verbose_name='Ответ (не верный)'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='false_answer_3',
            field=models.CharField(max_length=250, verbose_name='Ответ (не верный)'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='true_answer',
            field=models.CharField(max_length=250, verbose_name='Ответ (верный)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Номер вопроса'), (1, 'Вопрос 1'), (2, 'Вопрос 2'), (3, 'Вопрос 3'), (4, 'Вопрос 4'), (5, 'Вопрос 5'), (6, 'Вопрос 6'), (7, 'Вопрос 7'), (8, 'Вопрос 8'), (9, 'Вопрос 9'), (10, 'Вопрос 10')], verbose_name='Номер вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.quiz', verbose_name='Викторина'),
        ),
    ]
