# Generated by Django 5.0.2 on 2024-02-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_question_question_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='number_questions',
        ),
    ]
