# Generated by Django 5.0.2 on 2024-02-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_question_question_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('question_number', 'quiz'), name='unique_quiz_question_number'),
        ),
    ]
